Homework
Annolel/homework pull request #4
Opened 2020-02-22 08:25 UTC by Annolel

new PR with GIT homework

2020-02-24 11:07 UTC, Dgadavin requested changes

2020-02-24 11:07 UTC, Dgadavin commented on Ansible_homework/nginx/nginx_install.yml
> +    - name: phpinfo() to a file
Это не то

2020-02-24 11:07 UTC, Dgadavin commented on Ansible_homework/roles/jenkins/tasks/nginx.yml.save
> +---
кажется это дублирует main.yml

2020-02-24 11:07 UTC, Dgadavin commented on GIT_homework/Docker_homework/dockerfile.gitalp
> +ENTRYPOINT ["git", "pull"]
Нужно clone вместо pull

2020-02-24 11:07 UTC, Dgadavin commented on GIT_homework/your.json
>  {
Не валидный json

2020-02-24 11:07 UTC, Dgadavin commented on GIT_homework/Docker_homework/docker_command_list.txt
> +docker run -e X="<p>123</p>" -p 666:80 nginx1
Не желательно в переменную окружения передвать спец символы.

2020-02-24 18:50 UTC, Annolel commented on GIT_homework/your.json
>  {
я так понял что я забыл запятые. уже поправил. но я просто проверял мердж конфликт, и не особо смотрел чтоб там был правильный синтаксис.

2020-02-25 16:42 UTC, Annolel commented on GIT_homework/Docker_homework/dockerfile.gitalp
> +ENTRYPOINT ["git", "pull"]
исправил.

2020-03-25 21:00 UTC, merged